### PR TITLE
Create db

### PR DESCRIPTION
**Pull request by lingling287**

### CODE REVIEW

**Comment by TylerWasniowski** [comment]
Please remove the duplicates frontend files.

**Comment by TylerWasniowski** [comment]
Please take the later versions of the dependencies instead of the earlier versions.

**Comment by lingling287** [comment]
getting error when trying to login. Don't know if it's a dependency problem, front end problem, or routing problem. can someone help me take a look and see whats going on?

`Error occured while trying to proxy to: localhost:3000/login/submit `

@hien010 @TylerWasniowski

**Comment by lingling287** [comment]
Fixed it. Merging to master just removed the DB credentials from .env
I think all is good to merge to master.
@TylerWasniowski @hien010

**Comment by lingling287** [comment]
updated to latest dependencies. is it all okay now?

**Pull request merged**
